// vocabolari.dart

/// Vocabolario controllato per le USCITE
final Map<String, List<String>> vocabUscite = {
  'Casa': [
    'Affitto',
    'Mutuo',
    'Condominio',
    'TARI / Tassa rifiuti',
    'IMU / Property Tax',
    'Manutenzione ordinaria',
    'Manutenzione straordinaria',
    'Riparazioni idrauliche',
    'Riparazioni elettriche',
    'Riparazioni murarie',
    'Ristrutturazione',
    'Arredamento',
    'Elettrodomestici',
    'Prodotti per la casa',
    'Pulizie domestiche',
    'Giardinaggio',
    'Sicurezza casa / Allarme',
    'Assicurazione casa',
    'Spese notarili',
    'Spese agenzia immobiliare',
    'Affitto garage',
    'Affitto cantina',
    'Affitto posto auto',
    'Altro (Casa)',
  ],

  'Alimentazione': [
    'Spesa supermercato',
    'Spesa discount',
    'Spesa biologica',
    'Spesa mercato',
    'Prodotti freschi',
    'Prodotti surgelati',
    'Prodotti per la colazione',
    'Bevande analcoliche',
    'Bevande alcoliche',
    'Panificio',
    'Macelleria',
    'Pescheria',
    'Gastronomia',
    'Take-away',
    'Food delivery',
    'Catering',
    'Altro (Alimentazione)',
    ],

    'Ristorazione': [
    'Ristorante',
    'Trattoria',
    'Pizzeria',
    'Fast food',
    'Street food',
    'Bar / Caffetteria',
    'Colazione al bar',
    'Aperitivo',
    'Pasticceria',
    'Gelateria',
    'Altro (Ristorazione)',
  ],
  'Trasporti': [
    'Carburante',
    'Rifornimento GPL',
    'Rifornimento Metano',
    'Ricarica auto elettrica',
    'Ricarica scooter elettrico',
    'Pedaggi autostradali',
    'Parcheggi',
    'Parcheggi a pagamento',
    'Parcheggi multipiano',
    'Mezzi pubblici',
    'Autobus urbano',
    'Autobus extraurbano',
    'Metro',
    'Tram',
    'Treno regionale',
    'Treno alta velocità',
    'Taxi',
    'NCC / Chauffeur',
    'Car sharing',
    'Bike sharing',
    'Monopattino sharing',
    'Noleggio auto',
    'Noleggio scooter',
    'Noleggio bici',
    'Manutenzione auto',
    'Manutenzione moto',
    'Cambio gomme',
    'Assicurazione auto',
    'Assicurazione moto',
    'Bollo auto',
    'Bollo moto',
    'Lavaggio auto',
    'Lavaggio moto',
    'Altro (Trasporti)',
  ],
  'Salute e Benessere': [
    'Farmacia',
    'Parafarmacia',
    'Integratori',
    'Visita medica',
    'Visita specialistica',
    'Analisi del sangue',
    'Analisi di laboratorio',
    'Esami diagnostici',
    'Fisioterapia',
    'Osteopatia',
    'Chiropratica',
    'Dentista',
    'Igiene dentale',
    'Ottico / Occhiali',
    'Psicologo',
    'Psicoterapeuta',
    'Massaggi',
    'Benessere termale',
    'Spa / Centro benessere',
    'Palestra',
    'Personal trainer',
    'Piscina',
    'Corsi sportivi',
    'Yoga / Pilates',
    'Prodotti per la cura personale',
    'Cosmetici',
    'Parrucchiere',
    'Barbiere',
    'Estetista',
    'Altro (Salute e Benessere)',
  ],
  'Istruzione e Formazione': [
    'Libri scolastici',
    'Libri universitari',
    'Materiale scolastico',
    'Materiale didattico',
    'Cancelleria',
    'Corsi di formazione',
    'Corsi online',
    'Master / Specializzazioni',
    'Seminari / Workshop',
    'Webinar',
    'Ripetizioni',
    'Lezioni private',
    'Iscrizione scuola',
    'Iscrizione università',
    'Tasse universitarie',
    'Abbonamenti piattaforme educative',
    'Software educativi',
    'Certificazioni professionali',
    'Esami e test',
    'Convegni',
    'Conferenze',
    'Altro (Istruzione e Formazione)',
  ],
  'Tempo libero': [
    'Cinema',
    'Teatro',
    'Concerti',
    'Eventi culturali',
    'Musei',
    'Mostre',
    'Festival',
    'Sport e attività all’aperto',
    'Escursioni',
    'Gite fuori porta',
    'Viaggi brevi',
    'Weekend',
    'Abbonamenti streaming',
    'Abbonamenti musica',
    'Abbonamenti videogiochi',
    'Videogiochi',
    'Libri',
    'Fumetti',
    'Hobby creativi',
    'Modellismo',
    'Fotografia',
    'Strumenti musicali',
    'Corsi ricreativi',
    'Giochi da tavolo',
    'Puzzle',
    'Attività per bambini',
    'Parco divertimenti',
    'Bowling',
    'Biliardo',
    'Escape room',
    'Altro (Tempo libero)',
  ],
  'Abbigliamento': [
    'Abbigliamento uomo',
    'Abbigliamento donna',
    'Abbigliamento bambino',
    'Abbigliamento sportivo',
    'Abbigliamento lavoro',
    'Scarpe uomo',
    'Scarpe donna',
    'Scarpe bambino',
    'Accessori moda',
    'Borse',
    'Zaini',
    'Cappelli',
    'Guanti',
    'Sciarpe',
    'Cinture',
    'Intimo',
    'Calze',
    'Costumi da bagno',
    'Gioielli',
    'Orologi',
    'Occhiali da sole',
    'Riparazioni sartoriali',
    'Lavanderia / Stireria',
    'Altro (Abbigliamento)',
  ],
  'Tecnologia': [
    'Smartphone',
    'Tablet',
    'Computer portatile',
    'Computer fisso',
    'Monitor',
    'Stampante',
    'Accessori PC',
    'Accessori smartphone',
    'Cuffie / Auricolari',
    'Speaker / Audio',
    'Router / Modem',
    'Hard disk / SSD',
    'Memorie USB / SD',
    'Software',
    'Abbonamenti software',
    'Licenze professionali',
    'Servizi cloud',
    'Backup online',
    'Riparazioni smartphone',
    'Riparazioni computer',
    'Gaming console',
    'Videogiochi',
    'Accessori gaming',
    'Smartwatch',
    'Domotica',
    'Sicurezza smart',
    'Fotocamere',
    'Obiettivi fotografici',
    'Droni',
    'Altro (Tecnologia)',
  ],
  'Finanza e Banche': [
    'Prelievo bancomat',
    'Versamento contante',
    'Bonifico',
    'Commissioni bancarie',
    'Canone conto corrente',
    'Carta di credito',
    'Carta di debito',
    'Ricarica carta prepagata',
    'Interessi passivi',
    'Interessi attivi',
    'Investimenti',
    'Azioni',
    'Obbligazioni',
    'Fondi comuni',
    'ETF',
    'Piano di accumulo (PAC)',
    'Criptovalute',
    'Trading online',
    'Assicurazioni finanziarie',
    'Mutuo',
    'Rata mutuo',
    'Prestito personale',
    'Rata prestito',
    'Leasing',
    'Finanziamenti',
    'Spese notarili',
    'Consulenza finanziaria',
    'Altro (Finanza e Banche)',
  ],
  'Regali e Donazioni': [
    'Regali per famiglia',
    'Regali per amici',
    'Regali per partner',
    'Regali per bambini',
    'Regali di compleanno',
    'Regali di Natale',
    'Regali di anniversario',
    'Regali aziendali',
    'Fiori',
    'Cioccolatini / Dolci',
    'Buoni regalo',
    'Donazioni benefiche',
    'Donazioni ONG',
    'Donazioni religiose',
    'Crowdfunding',
    'Raccolte fondi',
    'Adozioni a distanza',
    'Volontariato (spese)',
    'Altro (Regali e Donazioni)',
  ],
  'Auto e Moto': [
    'Carburante',
    'Rifornimento GPL',
    'Rifornimento Metano',
    'Ricarica auto elettrica',
    'Ricarica moto elettrica',
    'Pedaggi autostradali',
    'Parcheggi',
    'Parcheggi a pagamento',
    'Parcheggi multipiano',
    'Assicurazione auto',
    'Assicurazione moto',
    'Bollo auto',
    'Bollo moto',
    'Tagliando auto',
    'Tagliando moto',
    'Cambio gomme',
    'Revisione auto',
    'Revisione moto',
    'Riparazioni auto',
    'Riparazioni moto',
    'Ricambi auto',
    'Ricambi moto',
    'Lavaggio auto',
    'Lavaggio moto',
    'Noleggio auto',
    'Noleggio moto',
    'Accessori auto',
    'Accessori moto',
    'Altro (Auto e Moto)',
  ],
  'Animali domestici': [
    'Cibo per animali',
    'Snack e premi',
    'Veterinario',
    'Vaccinazioni',
    'Visite di controllo',
    'Farmaci per animali',
    'Antiparassitari',
    'Toelettatura',
    'Lavaggio e taglio',
    'Accessori',
    'Guinzagli e pettorine',
    'Ciotole',
    'Giochi',
    'Cuccia / Letto',
    'Trasportino',
    'Lettiera e sabbia',
    'Pulizia e igiene',
    'Addestramento',
    'Pet sitter',
    'Pensione animali',
    'Assicurazione animali',
    'Altro (Animali domestici)',
  ],
  'Utenze': [
    'Energia elettrica',
    'Gas naturale',
    'Acqua',
    'Riscaldamento centralizzato',
    'Teleriscaldamento',
    'Internet fibra',
    'Internet ADSL',
    'Telefonia mobile',
    'Telefonia fissa',
    'TV a pagamento',
    'Canone RAI',
    'Ricariche telefoniche',
    'Servizi cloud domestici',
    'Manutenzione impianti',
    'Riparazioni idrauliche',
    'Riparazioni elettriche',
    'Altro (Utenze)',
  ],

};

/// Vocabolario controllato per le ENTRATE
final Map<String, List<String>> vocabEntrate = {
  'Stipendio': [
    'Stipendio mensile',
    'Stipendio settimanale',
    'Stipendio giornaliero',
    'Bonus aziendale',
    'Straordinari',
    'Tredicesima',
    'Quattordicesima',
    'Premi produzione',
    'Indennità',
    'Rimborsi spese',
    'Arretrati',
    'Liquidazione / TFR',
    'Altro (Stipendio)',
  ],

  'Lavoro autonomo': [
    'Fattura professionale',
    'Compenso occasionale',
    'Consulenza',
    'Prestazione freelance',
    'Royalties',
    'Diritti d’autore',
    'Vendita servizi',
    'Vendita prodotti',
    'Altro (Lavoro autonomo)',
  ],

  'Vendite': [
    'Vendita online',
    'Vendita usato',
    'Marketplace (eBay, Vinted, ecc.)',
    'Vendita oggetti personali',
    'Vendita beni aziendali',
    'Altro (Vendite)',
  ],

  'Interessi e investimenti': [
    'Interessi bancari',
    'Interessi deposito',
    'Dividendi',
    'Cedole obbligazionarie',
    'Profitti da trading',
    'Profitti da criptovalute',
    'Rendite finanziarie',
    'Cashback investimenti',
    'Altro (Investimenti)',
  ],

  'Affitti e proprietà': [
    'Affitto percepito',
    'Affitto breve (Airbnb)',
    'Affitto commerciale',
    'Affitto garage',
    'Affitto terreni',
    'Royalty immobiliari',
    'Altro (Affitti e proprietà)',
  ],

  'Rimborsi': [
    'Rimborso assicurativo',
    'Rimborso sanitario',
    'Rimborso aziendale',
    'Rimborso fiscale',
    'Rimborso spese varie',
    'Altro (Rimborsi)',
  ],

  'Pensioni e sussidi': [
    'Pensione',
    'Pensione di reversibilità',
    'NASPI',
    'Sussidi statali',
    'Indennità di maternità',
    'Indennità di malattia',
    'Altro (Pensioni e sussidi)',
  ],

  'Regali e donazioni ricevute': [
    'Regalo in denaro',
    'Donazione familiare',
    'Donazione privata',
    'Crowdfunding ricevuto',
    'Altro (Regali e donazioni)',
  ],

  'Altro': [
    'Entrata occasionale',
    'Ritrovamento denaro',
    'Cashback',
    'Premi e vincite',
    'Lotterie',
    'Concorsi',
    'Altro (Altro)',
  ],
};


/// Metodi di pagamento (per ora li lasciamo vuoti, li popoleremo dopo)
final List<String> metodiPagamentoBase = [
  'ACH (USA)',
  'Assegno',
  'Bancomat / Debito',
  'Bonifico bancario',
  'Bonifico internazionale (SWIFT)',
  'Bonifico SEPA',
  'Carta di credito',
  'Carta di debito',
  'Carta prepagata',
  'Cashback',
  'Contanti',
  'Criptovalute',
  'F24',
  'Google Pay',
  'IBAN virtuale',
  'Mastercard',
  'PagoPA',
  'PayPal',
  'POS fisico',
  'POS mobile',
  'Ricarica carta',
  'RID / Addebito diretto',
  'Satispay',
  'Stripe',
  'TransferWise / Wise',
  'Visa',
  'Wallet digitale',
  'Western Union',
  'Zelle (USA)',
  'Altro',
];